from enum import StrEnum


class ClaimOutcome(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class ProcessingStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    RULE_CHECK = "RULE_CHECK"
    INTERPRETING = "INTERPRETING"  # Phase 2: RAG + LLM reading of clinical notes
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReasonCode(StrEnum):
    """Machine-readable decision reasons. Also used as ground-truth labels in the benchmark."""

    # Structural validation (REJECTED)
    MALFORMED_CLAIM_NUMBER = "MALFORMED_CLAIM_NUMBER"
    MISSING_PROCEDURE_CODE = "MISSING_PROCEDURE_CODE"
    MISSING_DIAGNOSIS_CODE = "MISSING_DIAGNOSIS_CODE"
    INVALID_PROCEDURE_CODE_FORMAT = "INVALID_PROCEDURE_CODE_FORMAT"
    INVALID_DIAGNOSIS_CODE_FORMAT = "INVALID_DIAGNOSIS_CODE_FORMAT"
    INVALID_CLAIM_AMOUNT = "INVALID_CLAIM_AMOUNT"
    # Business rules (REJECTED)
    DUPLICATE_CLAIM = "DUPLICATE_CLAIM"
    DIAGNOSIS_PROCEDURE_MISMATCH = "DIAGNOSIS_PROCEDURE_MISMATCH"
    # Business rules (HUMAN_REVIEW)
    UNKNOWN_PROCEDURE_CODE = "UNKNOWN_PROCEDURE_CODE"
    MANUAL_REVIEW_REQUIRED_PROCEDURE = "MANUAL_REVIEW_REQUIRED_PROCEDURE"
    PROVIDER_ON_WATCHLIST = "PROVIDER_ON_WATCHLIST"
    HIGH_COST_CLAIM = "HIGH_COST_CLAIM"
    INSUFFICIENT_SUPPORTING_INFO = "INSUFFICIENT_SUPPORTING_INFO"
    AMBIGUOUS_CLINICAL_NOTES = "AMBIGUOUS_CLINICAL_NOTES"
    # Approval
    VALID_STANDARD_CLAIM = "VALID_STANDARD_CLAIM"
    # Phase 2 escalations to a human
    LLM_LOW_CONFIDENCE = "LLM_LOW_CONFIDENCE"
    LLM_PROCESSING_FALLBACK = "LLM_PROCESSING_FALLBACK"
    # Workflow failure
    PROCESSING_ERROR = "PROCESSING_ERROR"
